"""Add scenario rating model

Revision ID: f54ed3886c97
Revises: fbb78e50b2fa
Create Date: 2025-04-03 19:47:33.186031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f54ed3886c97'
down_revision = 'fbb78e50b2fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scenario_rating',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('scenario_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenario.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'scenario_id', name='unique_user_scenario_rating')
    )
    with op.batch_alter_table('scenario', schema=None) as batch_op:
        batch_op.alter_column('target_distance',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('stay_behind_line',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=10),
               existing_nullable=True)
        batch_op.alter_column('use_abilities',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=10),
               existing_nullable=True)
        batch_op.alter_column('no_ability_cooldown',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=10),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scenario', schema=None) as batch_op:
        batch_op.alter_column('no_ability_cooldown',
               existing_type=sa.String(length=10),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('use_abilities',
               existing_type=sa.String(length=10),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('stay_behind_line',
               existing_type=sa.String(length=10),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('target_distance',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)

    op.drop_table('scenario_rating')
    # ### end Alembic commands ###
